export const buildPageStateScript = (options?: {
  includeValues?: boolean;
}): string => {
  const includeValues = options?.includeValues === true;
  return [
    '(() => {',
    `  const includeValues = ${includeValues ? 'true' : 'false'};`,
    '  const escape = (value) => {',
    "    if (typeof CSS !== 'undefined' && typeof CSS.escape === 'function') {",
    '      return CSS.escape(value);',
    '    }',
    "    return String(value).replace(/[\"'\\\\]/g, '\\\\$&');",
    '  };',
    '  const truncate = (value, max) => {',
    "    const text = String(value ?? '');",
    '    return text.length > max ? text.slice(0, max) : text;',
    '  };',
    '  const redact = (value) => (includeValues ? truncate(value, 500) : "[redacted]");',
    '  const textFor = (element) => truncate((element?.textContent || "").replace(/\\s+/g, " ").trim(), 120);',
    '  const isVisible = (element) => {',
    '    if (!element || typeof element.getClientRects !== "function") {',
    '      return false;',
    '    }',
    '    const style = window.getComputedStyle(element);',
    '    if (style.display === "none" || style.visibility === "hidden") {',
    '      return false;',
    '    }',
    '    if (element.hidden || element.getAttribute("aria-hidden") === "true") {',
    '      return false;',
    '    }',
    '    return element.getClientRects().length > 0;',
    '  };',
    '  const selectorFor = (element) => {',
    '    if (!element || element.nodeType !== 1) {',
    '      return "";',
    '    }',
    '    if (element.id) {',
    '      return `#${escape(element.id)}`;',
    '    }',
    '    const testId = element.getAttribute("data-testid");',
    '    if (testId) {',
    '      return `[data-testid="${escape(testId)}"]`;',
    '    }',
    '    const name = element.getAttribute("name");',
    '    if (name) {',
    '      return `${element.tagName.toLowerCase()}[name="${escape(name)}"]`;',
    '    }',
    '    const ariaLabel = element.getAttribute("aria-label");',
    '    if (ariaLabel) {',
    '      return `${element.tagName.toLowerCase()}[aria-label="${escape(ariaLabel)}"]`;',
    '    }',
    '    const parts = [];',
    '    let node = element;',
    '    while (node && node.nodeType === 1 && parts.length < 4) {',
    '      let part = node.tagName.toLowerCase();',
    '      const parent = node.parentElement;',
    '      if (parent) {',
    '        const siblings = Array.from(parent.children).filter(',
    '          (child) => child.tagName === node.tagName',
    '        );',
    '        if (siblings.length > 1) {',
    '          part += `:nth-of-type(${siblings.indexOf(node) + 1})`;',
    '        }',
    '      }',
    '      parts.unshift(part);',
    '      node = parent;',
    '    }',
    "    return parts.join('>');",
    '  };',
    '  const labelFor = (element) => {',
    '    if (!element) {',
    '      return undefined;',
    '    }',
    '    const ariaLabel = element.getAttribute("aria-label");',
    '    if (ariaLabel) {',
    '      return truncate(ariaLabel, 120);',
    '    }',
    '    if (element.id) {',
    '      const explicitLabel = document.querySelector(`label[for="${escape(element.id)}"]`);',
    '      if (explicitLabel) {',
    '        return textFor(explicitLabel);',
    '      }',
    '    }',
    '    const parentLabel = element.closest("label");',
    '    if (parentLabel) {',
    '      return textFor(parentLabel);',
    '    }',
    '    return undefined;',
    '  };',
    '  const readStorage = (storage, limit) => {',
    '    try {',
    '      const keys = Object.keys(storage);',
    '      return {',
    '        count: keys.length,',
    '        entries: keys.slice(0, limit).map((key) => ({',
    '          key,',
    '          value: redact(storage.getItem(key)),',
    '        })),',
    '      };',
    '    } catch {',
    '      return { count: 0, entries: [] };',
    '    }',
    '  };',
    '  const forms = Array.from(document.querySelectorAll("form"))',
    '    .filter((form) => isVisible(form))',
    '    .map((form) => {',
    '      const fields = Array.from(form.elements)',
    '        .filter((element) => element && element.tagName)',
    '        .map((element) => {',
    '          const tag = element.tagName.toLowerCase();',
    '          const type = "type" in element && element.type ? element.type : tag;',
    '          const name = element.name || element.getAttribute("name") || element.id || "";',
    '          let value = "";',
    '          let options;',
    '          if (tag === "select") {',
    '            const select = element;',
    '            value = redact(select.value ?? "");',
    '            options = Array.from(select.options).map((option) => truncate(option.text, 120));',
    '          } else if (tag === "input" && element.type === "password") {',
    '            value = "[redacted]";',
    '          } else if (tag === "input" || tag === "textarea") {',
    '            value = redact(element.value ?? "");',
    '          } else if (element.isContentEditable) {',
    '            value = redact(element.textContent ?? "");',
    '          } else if ("value" in element) {',
    '            value = redact(element.value ?? "");',
    '          }',
    '          return {',
    '            name,',
    '            type,',
    '            value,',
    '            selector: selectorFor(element),',
    '            label: labelFor(element),',
    '            placeholder: truncate(element.getAttribute?.("placeholder") ?? "", 120) || undefined,',
    '            checked: typeof element.checked === "boolean" ? element.checked : undefined,',
    '            disabled: !!element.disabled,',
    '            visible: isVisible(element),',
    '            ...(options ? { options } : {}),',
    '          };',
    '        });',
    '      return {',
    '        selector: selectorFor(form),',
    '        action: form.getAttribute("action") || undefined,',
    '        method: form.getAttribute("method") || undefined,',
    '        fields,',
    '      };',
    '    });',
    '  const localStorageData = readStorage(window.localStorage, 25);',
    '  const sessionStorageData = readStorage(window.sessionStorage, 25);',
    '  const cookies = (document.cookie ? document.cookie.split(";") : [])',
    '    .map((entry) => entry.trim())',
    '    .filter((entry) => entry.length > 0)',
    '    .slice(0, 25)',
    '    .map((entry) => {',
    '      const [key, ...rest] = entry.split("=");',
    '      return {',
    '        key,',
    '        value: includeValues ? truncate(rest.join("="), 500) : "[redacted]",',
    '      };',
    '    });',
    '  const focused = document.activeElement && document.activeElement !== document.body',
    '    ? {',
    '        selector: selectorFor(document.activeElement),',
    '        name: document.activeElement.getAttribute?.("name") || document.activeElement.id || undefined,',
    '        label: labelFor(document.activeElement),',
    '        role: document.activeElement.getAttribute?.("role") || document.activeElement.tagName?.toLowerCase(),',
    '        type: document.activeElement.getAttribute?.("type") || undefined,',
    '        text: textFor(document.activeElement) || undefined,',
    '      }',
    '    : undefined;',
    '  const primaryActions = Array.from(document.querySelectorAll("button, a[href], input[type=button], input[type=submit]"))',
    '    .filter((element) => isVisible(element))',
    '    .map((element) => ({',
    '      selector: selectorFor(element),',
    '      role: element.getAttribute("role") || element.tagName.toLowerCase(),',
    '      name: truncate(element.getAttribute("aria-label") || element.innerText || element.value || "", 120),',
    '    }))',
    '    .filter((entry) => entry.name.length > 0)',
    '    .slice(0, 12);',
    '  return {',
    '    url: location.href,',
    '    title: document.title || undefined,',
    '    readyState: document.readyState || undefined,',
    '    focused,',
    '    primaryActions,',
    '    storageSummary: {',
    '      localStorageCount: localStorageData.count,',
    '      sessionStorageCount: sessionStorageData.count,',
    '      cookieCount: cookies.length,',
    '    },',
    '    forms,',
    '    localStorage: localStorageData.entries,',
    '    sessionStorage: sessionStorageData.entries,',
    '    cookies,',
    '  };',
    '})()',
  ].join('\n');
};
